apiVersion: v1
kind: Command
metadata:
  name: kick
  label:
    en_US: Kick User
    zh_Hans: 踢出成员
spec:
  command: kick
  description:
    en_US: 'Kick a user from group. Usage: !kick @user'
    zh_Hans: '踢出群成员。用法: !kick @用户'
execution:
  python:
    path: kick.py
    attr: KickCommand
