apiVersion: v1
kind: Command
metadata:
  name: mute
  label:
    en_US: Mute User
    zh_Hans: 禁言
spec:
  command: mute
  description:
    en_US: 'Mute a user. Usage: !mute @user 10m'
    zh_Hans: '禁言用户。用法: !mute @用户 10m'
execution:
  python:
    path: mute.py
    attr: MuteCommand
